cam_serial:
  baudrate: 115200
  bytesize: 8
  parity: N
  port: /dev/ttyS1
  stopbits: 1
  timeout: 1
camera:
  camera-fps: 30
  camera-height: 480
  camera-name: Camera
  camera-port: 0
  camera-type: Camera
  camera-width: 640
qr_serial:
  baudrate: 115200
  bytesize: 8
  parity: N
  port: /dev/ttyS2
  stopbits: 1
  timeout: 1
raybot:
  API_HOST: 0.0.0.0
  API_PORT: 80
  home_location: table_1
  max_distance_lift: 100
  max_distance_move: 100
  max_pwm_lift: 150
  max_pwm_movement: 150.0
  min_distance_lift: 21.0
  min_distance_move: 21.0
  parameter_motor: 4
  robot_name: Robot
  robot_type: Robot
serial:
  baudrate: 115200
  bytesize: 8
  parity: N
  port: COM5
  stopbits: 1
  timeout: 1
server:
  host: sandbox.order.cmsiot.net
  id: 2fff696d-7942-4e8c-b454-db8aafb57437
  password: admin
  path: /robots/ws-raybot?id=2fff696d-7942-4e8c-b454-db8aafb57437
  port: 443
  protocol: wss://
  ssl: true
  timeout: 10
  username: admin
